gems:
  - jekyll-paginate

title: Sweet 16
description:
    <a href="https://wordpress.org/themes/twentysixteen/" rel="external">Wordpress 2016 theme</a>
    in <a href="https://jekyllrb.com/" rel="external">Jekyll</a>

paginate: 10
permalink: /:title/

defaults:
  - scope:
        path: ""
    values:
        author: jdh8
